apiVersion: v1
kind: Service
metadata:
  name: {{ template "web.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}"
spec:
  ports:
    - port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}
  selector:
    component: "{{.Release.Name}}-{{.Values.component}}"
  type: {{ default "ClusterIP" .Values.serviceType | quote }}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "web.fullname" . }}
  labels:
    app: web
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}"
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{.Release.Name}}-{{.Values.component}}"
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-{{.Values.component}}"
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ printf "%s:%s" .Values.image .Values.global.imageTag }}"
          imagePullPolicy: {{.Values.imagePullPolicy}}
          ports:
          - name: http
            containerPort: {{.Values.containerPort }}
          env:
            - name: WORKFLOW_RELEASE
              value: {{.Release.Name | quote }}
            - name: NODE_ENV
              value: {{ default "" .Values.env.NODE_ENV | quote }}
            - name: DEBUG_ENABLED
              value: {{ default "" .Values.env.DEBUG_ENABLED | quote }}
            - name: API_URL
              value: {{ .Values.global.API_URL }}
            